### ISSUE TITLE
Multiple calls to setLocale only allows last to set locale content.

### ISSUE THREAD

**Issue by Trakkasure** [CherryProjects/translate-maker#11]
1: This only happens on the initial set of calls to setLocale.
2: Do not change the locale requesting, but change the namespace.
3: Only the last returned locale will exist in the data set. (clear is called on all calls)
This is because the options.locale is undefined in all calls to setLocale.
The locale is set only after the return of the file.

This will succeed if taking the returned promise from setLocale, and waiting for the first success before making further requests.
But other tools (react-translate-maker) do not wait before making subsequent calls for additional namespaces.

**Comment by seeden** [comment]
I will take a look on it. Thank you for your report

**Comment by Trakkasure** [comment]
Thanks

**Comment by seeden** [comment]
@Trakkasure  can you try latest 0.5.9 version of translate-maker?
I added waiting into the setLocale and added tests. It looks fine in this moment.
