### ISSUE TITLE
future of translate-maker

### ISSUE THREAD

**Issue by jamuhl** [CherryProjects/translate-maker#12]
Hi Zlatko,

Saw you put a lot of effort into this library...but wondering a little if there is a need for yet another i18n library (Don't get me wrong).

Coming from i18next (https://github.com/i18next/i18next) i know it's a lot of work and even harder to get an i18n library to be used.

i18next primary has it's on json format to work on (supports all the needs but even if adapted by some major translation management softwares - is not build on a standard). Beside that we provide gettext format support via our converter module.

I always thought about providing a ICU compatible translate "plugin" - means the default translate module on the i18next json format could be exchangable with another module. So one could use the benefits of i18next (language detection, backends) and also choose to use the ICU format.

Not sure if you would see benefit it joining that effort? If that's nothing you're interested just close this again...

Great to see what you've done so far and keep up.

Best, Jan

**Comment by seeden** [comment]
Hi @jamuhl thanks for your comment. I know i18next but I am not interested. 
Have a great day

**Comment by jamuhl** [comment]
Well ok. Would you mind to remove the i18next tag from your projects as it's not related in any way? As that is misleading i18next users.
