### ISSUE TITLE
Warning in webpack

### ISSUE THREAD

**Issue by anasbud** [CherryProjects/translate-maker#3]
I got this Warning whenever Webpack bundle my app :

> WARNING in ./~/translate-maker/dist/adapters/File.js
> Critical dependencies:
> 71:17-34 the request of a dependency is an expression
>  @ ./~/translate-maker/dist/adapters/File.js 71:17-34

I do not know if it is revelant in any way...

Thank you for your awesome work !

**Comment by seeden** [comment]
Hi @anasbud. Thank you for your comment. It is just a warning in the webpack. But I agree. It is ugly. I will try to change the behaviour of the file adapter.

**Comment by seeden** [comment]
It is fixed in the latest version
