### ISSUE TITLE
Locale event emitted before locale loaded

### ISSUE THREAD

**Issue by Trakkasure** [CherryProjects/translate-maker#4]
In the case of ajax or Webpack code splitting using File adapter, the locale event is emitted before the callback is called when the translations are actually available.

This cause issues, for example, with React in it's context. 

An adjustment of translate on line 115 moving 117 into a shim callback for the load callback should resolve this issue.

**Comment by seeden** [comment]
merged in new version 0.4.7
thank you @Trakkasure
